graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true


# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
# Datasource
  datasource:
    platform: h2
    url: jdbc:h2:mem:graphql;
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: 9999